2021-12-01 00:51:06.459357: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 00:51:06.460428: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 00:51:06.461469: "port" is not a valid port number for debugging
2021-12-01 00:51:06.462520: wfastcgi.py 3.0.0 initialized
2021-12-01 01:00:24.981942: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 01:00:24.982981: Running on_exit tasks
2021-12-01 01:00:24.982981: wfastcgi.py 3.0.0 closed
2021-12-01 01:40:47.258184: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 01:40:47.258742: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 01:40:47.259799: "port" is not a valid port number for debugging
2021-12-01 01:40:47.260848: wfastcgi.py 3.0.0 initialized
2021-12-01 01:46:00.917508: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 01:46:00.918547: Running on_exit tasks
2021-12-01 01:46:00.918547: wfastcgi.py 3.0.0 closed
2021-12-01 02:19:38.862595: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 02:19:38.863140: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 02:19:38.864183: "port" is not a valid port number for debugging
2021-12-01 02:19:38.864183: wfastcgi.py 3.0.0 initialized
2021-12-01 02:24:52.069422: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 02:24:52.070460: Running on_exit tasks
2021-12-01 02:24:52.070460: wfastcgi.py 3.0.0 closed
2021-12-01 04:53:14.045341: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 04:53:14.046368: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 04:53:14.047416: "port" is not a valid port number for debugging
2021-12-01 04:53:14.047416: wfastcgi.py 3.0.0 initialized
2021-12-01 04:58:27.681320: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 04:58:27.681849: Running on_exit tasks
2021-12-01 04:58:27.682887: wfastcgi.py 3.0.0 closed
2021-12-01 05:06:41.430955: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 05:06:41.431988: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 05:06:41.433029: "port" is not a valid port number for debugging
2021-12-01 05:06:41.433029: wfastcgi.py 3.0.0 initialized
2021-12-01 05:11:55.085446: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 05:11:55.086485: Running on_exit tasks
2021-12-01 05:11:55.086485: wfastcgi.py 3.0.0 closed
2021-12-01 05:40:33.199620: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 05:40:33.199620: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 05:40:33.200661: "port" is not a valid port number for debugging
2021-12-01 05:40:33.200661: wfastcgi.py 3.0.0 initialized
2021-12-01 05:45:46.767489: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 05:45:46.767489: Running on_exit tasks
2021-12-01 05:45:46.768534: wfastcgi.py 3.0.0 closed
2021-12-01 05:56:14.759975: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 05:56:14.759975: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 05:56:14.761007: "port" is not a valid port number for debugging
2021-12-01 05:56:14.762062: wfastcgi.py 3.0.0 initialized
2021-12-01 06:01:28.388583: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 06:01:28.389624: Running on_exit tasks
2021-12-01 06:01:28.389624: wfastcgi.py 3.0.0 closed
2021-12-01 06:19:44.376616: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 06:19:44.376616: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 06:19:44.377662: "port" is not a valid port number for debugging
2021-12-01 06:19:44.378697: wfastcgi.py 3.0.0 initialized
2021-12-01 06:24:57.981708: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 06:24:57.982734: Running on_exit tasks
2021-12-01 06:24:57.982734: wfastcgi.py 3.0.0 closed
2021-12-01 06:47:36.196886: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 06:47:36.196886: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 06:47:36.197923: "port" is not a valid port number for debugging
2021-12-01 06:47:36.198962: wfastcgi.py 3.0.0 initialized
2021-12-01 06:56:19.889062: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 06:56:19.890130: Running on_exit tasks
2021-12-01 06:56:19.890130: wfastcgi.py 3.0.0 closed
2021-12-01 07:41:08.776223: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 07:41:08.777251: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 07:41:08.778294: "port" is not a valid port number for debugging
2021-12-01 07:41:08.778294: wfastcgi.py 3.0.0 initialized
2021-12-01 07:46:22.283488: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 07:46:22.284537: Running on_exit tasks
2021-12-01 07:46:22.285102: wfastcgi.py 3.0.0 closed
2021-12-01 07:50:12.944763: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 07:50:12.945805: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 07:50:12.949462: "port" is not a valid port number for debugging
2021-12-01 07:50:12.951553: wfastcgi.py 3.0.0 initialized
2021-12-01 07:55:26.410598: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 07:55:26.411164: Running on_exit tasks
2021-12-01 07:55:26.412197: wfastcgi.py 3.0.0 closed
2021-12-01 08:08:50.045136: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 08:08:50.046183: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 08:08:50.046183: "port" is not a valid port number for debugging
2021-12-01 08:08:50.047223: wfastcgi.py 3.0.0 initialized
2021-12-01 08:14:38.711426: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 08:14:38.712467: Running on_exit tasks
2021-12-01 08:14:38.713010: wfastcgi.py 3.0.0 closed
2021-12-01 08:41:26.522344: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 08:41:26.523361: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 08:41:26.524399: "port" is not a valid port number for debugging
2021-12-01 08:41:26.524399: wfastcgi.py 3.0.0 initialized
2021-12-01 08:49:35.145610: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 08:49:35.146646: Running on_exit tasks
2021-12-01 08:49:35.146646: wfastcgi.py 3.0.0 closed
2021-12-01 09:33:21.218631: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 09:33:21.218631: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 09:33:21.219676: "port" is not a valid port number for debugging
2021-12-01 09:33:21.219676: wfastcgi.py 3.0.0 initialized
2021-12-01 09:42:04.808026: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 09:42:04.809082: Running on_exit tasks
2021-12-01 09:42:04.809082: wfastcgi.py 3.0.0 closed
2021-12-01 10:33:56.597710: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 10:33:56.598760: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 10:33:56.599800: "port" is not a valid port number for debugging
2021-12-01 10:33:56.600335: wfastcgi.py 3.0.0 initialized
2021-12-01 10:33:56.605524: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 10:33:56.605524: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 10:33:56.606552: "port" is not a valid port number for debugging
2021-12-01 10:33:56.606552: wfastcgi.py 3.0.0 initialized
2021-12-01 10:39:10.152965: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 10:39:10.154026: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 10:39:10.154026: Running on_exit tasks
2021-12-01 10:39:10.154577: Running on_exit tasks
2021-12-01 10:39:10.154577: wfastcgi.py 3.0.0 closed
2021-12-01 10:39:10.154577: wfastcgi.py 3.0.0 closed
2021-12-01 10:45:25.280805: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 10:45:25.281859: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 10:45:25.281859: "port" is not a valid port number for debugging
2021-12-01 10:45:25.282931: wfastcgi.py 3.0.0 initialized
2021-12-01 10:50:38.922772: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 10:50:38.923810: Running on_exit tasks
2021-12-01 10:50:38.923810: wfastcgi.py 3.0.0 closed
2021-12-01 10:56:26.485241: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 10:56:26.486310: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 10:56:26.487373: "port" is not a valid port number for debugging
2021-12-01 10:56:26.487373: wfastcgi.py 3.0.0 initialized
2021-12-01 11:01:40.077259: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 11:01:40.078321: Running on_exit tasks
2021-12-01 11:01:40.078321: wfastcgi.py 3.0.0 closed
2021-12-01 11:06:41.442250: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 11:06:41.443279: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 11:06:41.444319: "port" is not a valid port number for debugging
2021-12-01 11:06:41.444319: wfastcgi.py 3.0.0 initialized
2021-12-01 11:11:55.090382: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 11:11:55.091422: Running on_exit tasks
2021-12-01 11:11:55.091422: wfastcgi.py 3.0.0 closed
2021-12-01 11:47:11.909653: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 11:47:11.910691: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 11:47:11.911729: "port" is not a valid port number for debugging
2021-12-01 11:47:11.911729: wfastcgi.py 3.0.0 initialized
2021-12-01 11:52:25.489028: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 11:52:25.490084: Running on_exit tasks
2021-12-01 11:52:25.490084: wfastcgi.py 3.0.0 closed
2021-12-01 12:12:13.842008: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 12:12:13.843065: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 12:12:13.844114: "port" is not a valid port number for debugging
2021-12-01 12:12:13.844114: wfastcgi.py 3.0.0 initialized
2021-12-01 12:17:27.371627: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 12:17:27.372683: Running on_exit tasks
2021-12-01 12:17:27.372683: wfastcgi.py 3.0.0 closed
2021-12-01 12:40:37.395818: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 12:40:37.395818: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 12:40:37.396852: "port" is not a valid port number for debugging
2021-12-01 12:40:37.397877: wfastcgi.py 3.0.0 initialized
2021-12-01 12:44:33.820570: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 12:44:33.821623: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 12:44:33.821623: "port" is not a valid port number for debugging
2021-12-01 12:44:33.822681: wfastcgi.py 3.0.0 initialized
2021-12-01 12:49:55.830206: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 12:49:55.831269: Running on_exit tasks
2021-12-01 12:49:55.832321: wfastcgi.py 3.0.0 closed
2021-12-01 12:52:42.351773: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 12:52:42.351773: Running on_exit tasks
2021-12-01 12:52:42.352827: wfastcgi.py 3.0.0 closed
2021-12-01 14:06:45.604410: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 14:06:45.604952: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 14:06:45.606014: "port" is not a valid port number for debugging
2021-12-01 14:06:45.607063: wfastcgi.py 3.0.0 initialized
2021-12-01 14:11:59.057109: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 14:11:59.057680: Running on_exit tasks
2021-12-01 14:11:59.058717: wfastcgi.py 3.0.0 closed
2021-12-01 15:36:36.995904: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 15:36:36.996938: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 15:36:36.997979: "port" is not a valid port number for debugging
2021-12-01 15:36:36.997979: wfastcgi.py 3.0.0 initialized
2021-12-01 15:41:50.616244: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 15:41:50.616244: Running on_exit tasks
2021-12-01 15:41:50.617293: wfastcgi.py 3.0.0 closed
2021-12-01 15:58:24.706038: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 15:58:24.707065: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 15:58:24.708100: "port" is not a valid port number for debugging
2021-12-01 15:58:24.709135: wfastcgi.py 3.0.0 initialized
2021-12-01 16:03:38.259415: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 16:03:38.260456: Running on_exit tasks
2021-12-01 16:03:38.261024: wfastcgi.py 3.0.0 closed
2021-12-01 17:46:30.007675: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 17:46:30.008723: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 17:46:30.009772: "port" is not a valid port number for debugging
2021-12-01 17:46:30.010823: wfastcgi.py 3.0.0 initialized
2021-12-01 17:52:53.617903: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 17:52:53.618460: Running on_exit tasks
2021-12-01 17:52:53.618460: wfastcgi.py 3.0.0 closed
2021-12-01 18:16:50.240180: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 18:16:50.241232: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 18:16:50.242298: "port" is not a valid port number for debugging
2021-12-01 18:16:50.243330: wfastcgi.py 3.0.0 initialized
2021-12-01 18:22:02.232951: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 18:22:02.234024: Running on_exit tasks
2021-12-01 18:22:02.235072: wfastcgi.py 3.0.0 closed
2021-12-01 18:36:41.202744: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 18:36:41.203755: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 18:36:41.204805: "port" is not a valid port number for debugging
2021-12-01 18:36:41.204805: wfastcgi.py 3.0.0 initialized
2021-12-01 18:36:42.306572: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 18:36:42.313034: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 18:36:42.316243: "port" is not a valid port number for debugging
2021-12-01 18:36:42.335828: wfastcgi.py 3.0.0 initialized
2021-12-01 18:39:52.780497: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 18:39:52.781536: Running on_exit tasks
ause mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 18:39:52.781536: Running on_exit tasks
2021-12-01 18:49:29.328889: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 18:49:29.329955: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 18:49:29.330967: "port" is not a valid port number for debugging
2021-12-01 18:49:29.332003: wfastcgi.py 3.0.0 initialized
2021-12-01 19:42:27.790908: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 19:42:27.801881: Running on_exit tasks
2021-12-01 19:42:27.803494: wfastcgi.py 3.0.0 closed
2021-12-01 19:42:57.710000: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 19:42:57.711048: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 19:42:57.712090: "port" is not a valid port number for debugging
2021-12-01 19:42:57.713143: wfastcgi.py 3.0.0 initialized
2021-12-01 19:49:21.618143: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 19:49:21.618718: Running on_exit tasks
2021-12-01 19:49:21.620970: wfastcgi.py 3.0.0 closed
2021-12-01 19:52:01.996001: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 19:52:01.997031: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 19:52:01.998093: "port" is not a valid port number for debugging
2021-12-01 19:52:01.999135: wfastcgi.py 3.0.0 initialized
2021-12-01 19:52:59.338772: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 19:52:59.338772: Running on_exit tasks
2021-12-01 19:54:52.639413: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 19:54:52.639413: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 19:54:52.641524: "port" is not a valid port number for debugging
2021-12-01 19:54:52.641524: wfastcgi.py 3.0.0 initialized
2021-12-01 20:13:34.988889: wfastcgi.py exiting because masterspace\models.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:13:34.989934: Running on_exit tasks
2021-12-01 20:16:56.772637: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:16:56.773645: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:16:56.774680: "port" is not a valid port number for debugging
2021-12-01 20:16:56.774680: wfastcgi.py 3.0.0 initialized
2021-12-01 20:28:35.162778: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:28:35.163805: Running on_exit tasks
2021-12-01 20:29:10.223219: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:29:10.224254: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:29:10.224799: "port" is not a valid port number for debugging
2021-12-01 20:29:10.225833: wfastcgi.py 3.0.0 initialized
2021-12-01 20:33:02.955788: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:33:02.956820: Running on_exit tasks
2021-12-01 20:33:44.606216: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:33:44.607244: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:33:44.608845: "port" is not a valid port number for debugging
2021-12-01 20:33:44.608845: wfastcgi.py 3.0.0 initialized
2021-12-01 20:36:28.795424: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:36:28.796481: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:36:28.797516: "port" is not a valid port number for debugging
2021-12-01 20:36:28.798563: wfastcgi.py 3.0.0 initialized
2021-12-01 20:36:28.800660: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:36:28.801207: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:36:28.806397: "port" is not a valid port number for debugging
2021-12-01 20:36:28.807424: wfastcgi.py 3.0.0 initialized
2021-12-01 20:37:25.811441: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:37:25.817191: Running on_exit tasks
2021-12-01 20:37:25.819282: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:37:25.820877: Running on_exit tasks
2021-12-01 20:37:25.833521: wfastcgi.py exiting because mss_website\settings.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:37:25.843403: Running on_exit tasks
2021-12-01 20:39:31.171539: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:39:31.172111: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:39:31.173140: "port" is not a valid port number for debugging
2021-12-01 20:39:31.174165: wfastcgi.py 3.0.0 initialized
2021-12-01 20:42:43.135365: wfastcgi.py exiting because masterspace\models.py has changed, matching .*((\.py)|(\.config))$
2021-12-01 20:42:43.136885: Running on_exit tasks
2021-12-01 20:44:57.263264: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:44:57.264310: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:44:57.265348: "port" is not a valid port number for debugging
2021-12-01 20:44:57.267437: wfastcgi.py 3.0.0 initialized
2021-12-01 20:45:01.195113: Failed to import applicationinsights: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 639, in read_wsgi_handler
    from applicationinsights.requests import WSGIApplication
ModuleNotFoundError: No module named 'applicationinsights'
2021-12-01 20:45:01.196158: wfastcgi.py will restart when files in C:\inetpub\wwwroot\msswebsite\ are changed: .*((\.py)|(\.config))$
2021-12-01 20:45:01.196720: "port" is not a valid port number for debugging
2021-12-01 20:45:01.197764: wfastcgi.py 3.0.0 initialized
2021-12-01 20:50:11.547479: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 20:50:11.548514: Running on_exit tasks
2021-12-01 20:50:11.548514: wfastcgi.py 3.0.0 closed
2021-12-01 21:25:15.487004: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "C:\inetpub\wwwroot\msswebsite\env\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-12-01 21:25:15.488057: Running on_exit tasks
2021-12-01 21:25:15.489082: wfastcgi.py 3.0.0 closed
